### ISSUE TITLE
bug found in testing 

### ISSUE THREAD

**Issue by aberry22** [Macaela-Morrison/IS147-Group-A-Project#12]
![image](https://github.com/user-attachments/assets/a9042434-473d-4fc2-bb54-26f04858c5a9)
 
error message when I input my expense amount

**Comment by aberry22** [comment]
^I just re-ran the code and again and chose the same pathway and I didn't have an issue most likely just a glitch.

**Comment by aberry22** [comment]
When inputting number 3. view totals it re-routes me to the menu

**Comment by Macaela-Morrison** [comment]
1) For the amount input the user should only input a number ie. 34, not $34. @lbryso Would you mind adding an extra instruction on that line with an example so the user knows? 

2) As of now the search is not implemented yet so the behavior is correct. I plan to implement the search next and will let you know when you can retest it.

3) I think allowing numbers for the name is ok since the user can name an expense whatever they want. But we can discuss adding some validation here if you think it should be changed. Maybe require the name to start with a character so you can have something like Groceries2, but not 2. What do you think?

**Comment by aberry22** [comment]
Okay sounds good just let me know when I should retest the user input. Yes I do think a variation of letters and numbers is good. I thought there was nothing wrong with it allowing the numbers however I just wanted to make sure it wasn't something we were going to get points off for.

**Comment by lbryso** [comment]
I am on it!

**Comment by Macaela-Morrison** [comment]
I am re-opening this issue as a new feature has been added. Users can now edit the expense. 

The search functionality will be implemented next

I added a $ symbol to the input for the amount when adding an expense. I think that will be a good hint for the user to only enter a number. We can add extra validation if time allows.

**Comment by Macaela-Morrison** [comment]
Added capabilities to view overall totals from the main menu. I am still implementing the yearly total and search method. But you can start testing the new methods

**Comment by Macaela-Morrison** [comment]
Closing issue since bugs have been resolved
